services:
  - type: web
    name: unisync
    rootDir: server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.rwqhkghyqupucjuonkoi:Macnitosh%40@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: UniSync <noreply@unisync.com>
