services:
  - type: web
    name: unisync
    root: server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:Macnitosh%4012@db.rwqhkghyqupucjuonkoi.supabase.co:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
